language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  # Force the latest firefox, otherwise we get and old ESR version
  # that we dont even support
  firefox: latest
  apt:
    packages:
    - firefox
    - xvfb
before_script:
  # start xvfb and firefox to run the tests
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - sleep 3 # give xvfb some time to start
  - export DISPLAY=:99.0
  - which firefox
  # install geckodriver
  - bin/download_geckodriver
  - export PATH=$PATH:$HOME/.cargo/bin:$PWD/bin
  - which geckodriver
script:
  - RUST_LOG="webdriver=trace" cargo test --verbose -- --test-threads=1
