language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  # Force the latest firefox, otherwise we get an old ESR version
  # that we don't even support
  firefox: latest
  chrome: stable
  apt:
    packages:
    - xvfb
before_script:
  - source bin/travis/before
  # install chromedriver
  - bin/download_chromedriver
  - export CHROME_BIN=/usr/bin/google-chrome-stable
  - export CHROME_HEADLESS=1
  - which chromedriver
script:
  - TC="${TRAVIS_RUST_VERSION}" bin/build_tc
