language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  # Force the latest firefox, otherwise we get and old ESR version
  # that we dont even support
  firefox: latest
  chrome: stable
  apt:
    packages:
    - xvfb
before_script:
  # start xvfb and firefox to run the tests
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - sleep 3 # give xvfb some time to start
  - export DISPLAY=:99.0
  - which firefox
  # install geckodriver
  - bin/download_geckodriver
  - export PATH=$PATH:$HOME/.cargo/bin:$PWD/bin
  - which geckodriver
  # install chromedriver
  - bin/download_chromedriver
  - export CHROME_BIN=/usr/bin/google-chrome-stable
  - export CHROME_HEADLESS=1
  - which chromedriver
script:
  - TC="${TRAVIS_RUST_VERSION}" bin/build_tc
