[package]
name = "webdriver_client"
version = "0.1.0"
authors = ["raf",
           "Alex Helfet <alex.helfet@gmail.com>"]

[dependencies]
hyper = "^0.10"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
log = "^0.3"
rand = "^0.3"
rustyline = { version = "^1.0", optional = true }
stderrlog = "^0.2"

[dev-dependencies]
env_logger = "^0.4"

[features]
default = []
shell = ["rustyline"]

[[bin]]
name = "www"
path = "src/bin/www.rs"
required-features = ["shell"]
