[package]
name = "webdriver"
version = "0.1.0"
authors = ["raf"]

[dependencies]
hyper = "^0.10"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
log = "^0.3"
rand = "^0.3"
rustyline = "^1.0"
stderrlog = "^0.2"
